spring.application.name=Brisa-Sur-Aromas

# ===============================
# BASE DE DATOS POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/brisasur_db
spring.datasource.username=postgres
spring.datasource.password=tu_contraseña_aqui
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# OBSERVABILIDAD Y MÉTRICAS (DEVOPS)
# ===============================
# Habilitar endpoints para Prometheus y Health Checks
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}